# Generated by Django 5.1.6 on 2025-06-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dates_for_list_view',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('recursion_type', models.CharField(choices=[('one_time', 'One-Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('interval', 'Every Nth Day/Week/Month'), ('weekday', 'Weekday (e.g., every Monday)'), ('relative', 'Relative (e.g., every 2nd Monday of the month)')], default='one_time', max_length=150)),
                ('relative_n', models.CharField(blank=True, choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('last', 'Last'), ('nth', 'Nth')], max_length=100, null=True)),
                ('relative_day_or_interval', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('weekday', 'Weekday'), ('weekend_day', 'Weekend day (Sat or Sun)')], max_length=100, null=True)),
                ('relative_timeframe', models.CharField(blank=True, choices=[('month', 'Month'), ('year', 'Year')], max_length=100, null=True)),
                ('interval_n', models.IntegerField(blank=True, null=True)),
                ('interval_timeframe', models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day')], max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='calendar_grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('day_rank_month', models.IntegerField()),
                ('day_rank_year', models.IntegerField()),
                ('is_booked', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'date'), name='unique_date')],
            },
        ),
    ]
