# Generated by Django 5.1.6 on 2025-06-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar_grid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('day_rank_month', models.IntegerField(blank=True, null=True)),
                ('day_rank_year', models.IntegerField(blank=True, null=True)),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('recursion_type', models.CharField(choices=[('one_time', 'One-Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('interval', 'Every Nth Day/Week/Month'), ('weekday', 'Weekday (e.g., every Monday)'), ('relative', 'Relative (e.g., every 2nd Monday of the month)')], default='one_time', max_length=150)),
                ('relative_n', models.CharField(blank=True, choices=[('1', 'First'), ('2', 'Second'), ('3', 'Third'), ('last', 'Last'), ('nth', 'Nth')], max_length=100, null=True)),
                ('relative_day_or_interval', models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday'), ('weekday', 'Weekday'), ('weekend_day', 'Weekend day (Sat or Sun)')], max_length=100, null=True)),
                ('relative_timeframe', models.CharField(blank=True, choices=[('month', 'Month'), ('year', 'Year')], max_length=100, null=True)),
                ('interval_n', models.IntegerField(blank=True, null=True)),
                ('interval_timeframe', models.CharField(blank=True, choices=[('year', 'Year'), ('month', 'Month'), ('week', 'Week'), ('day', 'Day')], max_length=150, null=True)),
                ('weekday_choice', models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='personal_events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'event', 'date'), name='unique_event')],
            },
        ),
    ]
