# Generated by Django 5.1.6 on 2025-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0003_eventlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='weekday_choice',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True),
        ),
    ]
