# Generated by Django 5.1.6 on 2025-06-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0004_alter_event_weekday_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar_grid',
            old_name='date',
            new_name='day',
        ),
    ]
