# Generated by Django 5.1.6 on 2025-06-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0005_rename_date_calendar_grid_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='relative_day_or_interval',
            field=models.CharField(blank=True, choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday'), ('weekday', 'Weekday'), ('weekend', 'Weekend day (Sat or Sun)')], max_length=100, null=True),
        ),
    ]
