# Generated by Django 5.1.6 on 2025-06-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0006_alter_event_relative_day_or_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_grid',
            name='full_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
