# Generated by Django 5.1.6 on 2025-06-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0007_calendar_grid_full_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar_grid',
            name='full_date',
        ),
    ]
