# Generated by Django 5.1.6 on 2025-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0008_remove_calendar_grid_full_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_grid',
            name='full_date',
            field=models.DateField(null=True),
        ),
    ]
