# Generated by Django 5.1.6 on 2025-06-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0009_calendar_grid_full_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('work_event', 'Work event'), ('personal_event', 'Personal event')], default='personal_event', max_length=150),
        ),
    ]
