# Generated by Django 5.1.6 on 2025-06-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0011_alter_event_relative_n_alter_eventlist_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
    ]
