# Generated by Django 5.2.2 on 2025-06-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_events', '0012_remove_event_event_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calendar_grid',
            constraint=models.UniqueConstraint(fields=('full_date',), name='unique_full_date'),
        ),
    ]
